### ISSUE TITLE
Crafted items go nowhere

### ISSUE THREAD

**Issue by LemonGraham** [magicskysword/CraftMaster#4]
It seems after crafting a new item, or upgrading an already existing magical item, the newly created/upgraded item does not get added to the inventory or personal chest. 

If it is added somewhere else, please let me know

**Comment by magicskysword** [comment]
Yes, this is a bug that seems to have been caused by me forgetting to clean up the project when I was building. I have recompiled the new version to fix the Bug.

**Comment by LemonGraham** [comment]
Amazing! Thank you!
