### ISSUE TITLE
Can not enchant crafted items

### ISSUE THREAD

**Issue by LemonGraham** [magicskysword/CraftMaster#5]
I can not enchant equipment created through this mod's crafting. Specifically, I am trying to enchant an Earthbreaker, but every time I select an earth breaker that the mod created, the menu crashes.

**Comment by LemonGraham** [comment]
Note: This is also for weapons already enchanted once from the mod

**Comment by magicskysword** [comment]
Please check if the mod version is the latest version. Version 0.3.2 has fixed the Bug.
You can update this mod from the [ModFinder](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder).

**Comment by LemonGraham** [comment]
![Screenshot (793)](https://github.com/magicskysword/CraftMaster/assets/21150416/adc637bf-5db5-4ac2-b5b7-f7b7b2e7ee9b)

Mod is up to date, and the problem persists. It's a different issue than my last reported one, the game is able to create new weapons and enchant them, however it can not enchant weapons it has previously enchanted or ones that it previously created

**Comment by magicskysword** [comment]
Sorry, I reproduced the bug. It's been fixed now.

**Comment by LemonGraham** [comment]
Thank you, I have updated and it is working as intended
